development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: async

staging:
  adapter: redis
  url: redis://localhost:6379

production:
  adapter: redis
  url: redis://localhost:6379